highlighter: rouge
permalink: /:title/
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
comments: true
exclude: ['.git']
name: "charlie drage"
description: "charlie drage - traveler, linux administrator, software developer"
